packages:
  - 'lix/packages/*'
  - 'lix/website'
  - '!lix/packages/exp'
  - 'inlang/development-projects/*'
  - 'inlang/source-code/*'
  - 'inlang/source-code/recommendations/*'
  - 'inlang/source-code/plugins/*'
  - 'inlang/source-code/paraglide/*'
  - 'inlang/source-code/ide-extension/src/webviews/*'
  - 'inlang/source-code/end-to-end-tests/*'
  - 'inlang/source-code/paraglide/paraglide-vite/tests/*'
  - 'inlang/source-code/paraglide/*/example'
  - 'inlang/source-code/paraglide/paraglide-next/examples/*'
  - 'inlang/source-code/templates/*'
  - 'inlang/source-code/message-lint-rules/*'
  - 'inlang/source-code/versioned-interfaces/*'
  - 'inlang/source-code/sdk-v2/sample-app'
